import fs from 'node:fs/promises';
const data = JSON.parse(await fs.readFile('.codex-tmp/2025_stats_matched.json', 'utf8'));
const lines = [];
lines.push('-- 2025 DRAFT PREP PERFORMANCE IMPORT');
lines.push('-- Source file: 2025_Draft_Prep_Stats.docx');
lines.push('-- Updates only temporary 2025 scouting/performance fields.');
lines.push('');
lines.push('with stats_import (');
lines.push('  player_id,');
lines.push('  avg_draft_position,');
lines.push('  total_earnings,');
lines.push('  best_finish,');
lines.push('  draft_value_index');
lines.push(') as (');
lines.push('  values');
data.matches.forEach((item, index) => {
  const q = (value) => value === null || value === undefined ? 'null' : `'${String(value).replace(/'/g, "''")}'`;
  const n = (value) => value === null || !Number.isFinite(value) ? 'null' : String(value);
  const suffix = index === data.matches.length - 1 ? '' : ',';
  lines.push(`    ('${item.player.id}'::uuid, ${n(item.scouting_2025_avg_draft_position)}::numeric, ${n(item.scouting_2025_total_earnings)}::numeric, ${q(item.scouting_2025_best_finish)}::text, ${q(item.scouting_2025_draft_value_index)}::text)${suffix}`);
});
lines.push(')');
lines.push('update public.players as p');
lines.push('set scouting_2025_avg_draft_position = si.avg_draft_position,');
lines.push('    scouting_2025_total_earnings = si.total_earnings,');
lines.push('    scouting_2025_best_finish = si.best_finish,');
lines.push('    scouting_2025_draft_value_index = si.draft_value_index,');
lines.push('    updated_at = now()');
lines.push('from stats_import as si');
lines.push('where p.id = si.player_id;');
lines.push('');
await fs.writeFile('supabase/2025_draft_prep_stats_import.sql', lines.join('\n'));
console.log(JSON.stringify({ updates: data.matches.length, unmatched: data.unmatched, file: 'supabase/2025_draft_prep_stats_import.sql', lines: lines.length }, null, 2));
