export type PlayerRank = "A" | "B" | "C" | "D";

export type CampPlayer = {
  name: string;
  slug: string;
  initials: string;
  room: string;
  arrival: string;
  rank: PlayerRank;
  handicap: string;
  notes: string;
  contact: string;
};

export const players: CampPlayer[] = [
  {
    name: "Nick Blacklock",
    slug: "nick-blacklock",
    initials: "NB",
    room: "1",
    arrival: "Monday PM",
    rank: "A",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Nick Joyce",
    slug: "nick-joyce",
    initials: "NJ",
    room: "1",
    arrival: "Tuesday PM NO GOLF",
    rank: "B",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Nathan Bunch",
    slug: "nathan-bunch",
    initials: "NB",
    room: "1",
    arrival: "Wednesday PM",
    rank: "C",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Kris Yoder",
    slug: "kris-yoder",
    initials: "KY",
    room: "1",
    arrival: "Wednesday PM",
    rank: "D",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Jon Nickel",
    slug: "jon-nickel",
    initials: "JN",
    room: "2",
    arrival: "Tuesday PM NO GOLF",
    rank: "B",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Joe Fulk",
    slug: "joe-fulk",
    initials: "JF",
    room: "2",
    arrival: "Tuesday PM NO GOLF",
    rank: "C",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Luke Merriman",
    slug: "luke-merriman",
    initials: "LM",
    room: "2",
    arrival: "Tuesday PM NO GOLF",
    rank: "A",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Adam Hedrick",
    slug: "adam-hedrick",
    initials: "AH",
    room: "2",
    arrival: "Tuesday PM NO GOLF",
    rank: "D",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Alex Aust",
    slug: "alex-aust",
    initials: "AA",
    room: "3",
    arrival: "Monday PM",
    rank: "B",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Scott Felix",
    slug: "scott-felix",
    initials: "SF",
    room: "3",
    arrival: "Tuesday PM GOLF",
    rank: "C",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Jacob Koch",
    slug: "jacob-koch",
    initials: "JK",
    room: "3",
    arrival: "Tuesday PM GOLF",
    rank: "A",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Doug Anewalt",
    slug: "doug-anewalt",
    initials: "DA",
    room: "3",
    arrival: "Wednesday AM",
    rank: "D",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Dustin Hudson",
    slug: "dustin-hudson",
    initials: "DH",
    room: "4",
    arrival: "Tuesday PM GOLF",
    rank: "A",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Shawn Ice",
    slug: "shawn-ice",
    initials: "SI",
    room: "4",
    arrival: "Tuesday PM GOLF",
    rank: "B",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Jared Knight",
    slug: "jared-knight",
    initials: "JK",
    room: "4",
    arrival: "Monday PM",
    rank: "C",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Chris Romero",
    slug: "chris-romero",
    initials: "CR",
    room: "4",
    arrival: "Monday PM",
    rank: "D",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Kevin Schofield",
    slug: "kevin-schofield",
    initials: "KS",
    room: "5",
    arrival: "Tuesday PM NO GOLF",
    rank: "B",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Tyler Schrohe",
    slug: "tyler-schrohe",
    initials: "TS",
    room: "5",
    arrival: "Monday PM",
    rank: "C",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Clayton Hooks",
    slug: "clayton-hooks",
    initials: "CH",
    room: "5",
    arrival: "Tuesday PM GOLF",
    rank: "A",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Cameron Carter",
    slug: "cameron-carter",
    initials: "CC",
    room: "5",
    arrival: "Wednesday AM",
    rank: "D",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Shane Loeffler",
    slug: "shane-loeffler",
    initials: "SL",
    room: "6",
    arrival: "Monday PM",
    rank: "A",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Mike Case",
    slug: "mike-case",
    initials: "MC",
    room: "6",
    arrival: "Wednesday PM",
    rank: "B",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Jamie Miles",
    slug: "jamie-miles",
    initials: "JM",
    room: "6",
    arrival: "Wednesday PM",
    rank: "C",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Shawn Bennett",
    slug: "shawn-bennett",
    initials: "SB",
    room: "6",
    arrival: "Tuesday PM GOLF",
    rank: "D",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Jesse Praeuner",
    slug: "jesse-praeuner",
    initials: "JP",
    room: "7",
    arrival: "Tuesday PM GOLF",
    rank: "A",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Dave Praeuner",
    slug: "dave-praeuner",
    initials: "DP",
    room: "7",
    arrival: "Tuesday PM GOLF",
    rank: "B",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Clayton Allen",
    slug: "clayton-allen",
    initials: "CA",
    room: "7",
    arrival: "Tuesday PM NO GOLF",
    rank: "C",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Justin Moody",
    slug: "justin-moody",
    initials: "JM",
    room: "7",
    arrival: "Tuesday PM GOLF",
    rank: "D",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Sam Kemp",
    slug: "sam-kemp",
    initials: "SK",
    room: "8",
    arrival: "Tuesday PM GOLF",
    rank: "B",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Andrew Dimino",
    slug: "andrew-dimino",
    initials: "AD",
    room: "8",
    arrival: "Tuesday PM GOLF",
    rank: "C",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Chris Kerns",
    slug: "chris-kerns",
    initials: "CK",
    room: "8",
    arrival: "Tuesday PM NO GOLF",
    rank: "A",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Matt Galley",
    slug: "matt-galley",
    initials: "MG",
    room: "8",
    arrival: "TBD",
    rank: "D",
    handicap: "TBD",
    notes: "Arrival not visible in roster image.",
    contact: "Coming soon",
  },
  {
    name: "Austin Hartshorn",
    slug: "austin-hartshorn",
    initials: "AH",
    room: "9",
    arrival: "Tuesday PM GOLF",
    rank: "B",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Tyler Hofmann",
    slug: "tyler-hofmann",
    initials: "TH",
    room: "9",
    arrival: "Tuesday PM GOLF",
    rank: "C",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Andrew Peretin",
    slug: "andrew-peretin",
    initials: "AP",
    room: "9",
    arrival: "Tuesday PM GOLF",
    rank: "D",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Adam Hartshorn",
    slug: "adam-hartshorn",
    initials: "AH",
    room: "9",
    arrival: "Tuesday PM GOLF",
    rank: "A",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Rob LaPlante",
    slug: "rob-laplante",
    initials: "RL",
    room: "10",
    arrival: "Tuesday PM GOLF",
    rank: "A",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "James Peel",
    slug: "james-peel",
    initials: "JP",
    room: "10",
    arrival: "Monday PM",
    rank: "B",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Jim Smith",
    slug: "jim-smith",
    initials: "JS",
    room: "10",
    arrival: "Wednesday AM",
    rank: "C",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Max Utter",
    slug: "max-utter",
    initials: "MU",
    room: "10",
    arrival: "Wednesday AM",
    rank: "D",
    handicap: "TBD",
    notes: "Roster image source.",
    contact: "Coming soon",
  },
  {
    name: "Todd Anderson",
    slug: "todd-anderson",
    initials: "TA",
    room: "No Room",
    arrival: "Wednesday PM",
    rank: "C",
    handicap: "TBD",
    notes: "Listed without a room in roster image.",
    contact: "Coming soon",
  },
];

function getLastName(player: CampPlayer) {
  const nameParts = player.name.trim().split(/\s+/);

  return nameParts[nameParts.length - 1] || player.name;
}

export const playersByLastName = [...players].sort((a, b) => {
  const lastNameCompare = getLastName(a).localeCompare(getLastName(b));

  if (lastNameCompare !== 0) {
    return lastNameCompare;
  }

  return a.name.localeCompare(b.name);
});

export const roomAssignments = Object.values(
  players.reduce<
    Record<string, { room: string; players: CampPlayer[]; arrivals: string[] }>
  >((accumulator, player) => {
    if (!accumulator[player.room]) {
      accumulator[player.room] = {
        room: player.room,
        players: [],
        arrivals: [],
      };
    }

    accumulator[player.room].players.push(player);

    if (!accumulator[player.room].arrivals.includes(player.arrival)) {
      accumulator[player.room].arrivals.push(player.arrival);
    }

    return accumulator;
  }, {}),
).sort((a, b) => a.room.localeCompare(b.room));

export function getPlayerBySlug(slug: string) {
  return players.find((player) => player.slug === slug);
}
